language: java
jdk:
  - openjdk11

dist: trusty

# Need kafka for integration tests
before_install:
  - wget "https://www.apache.org/dyn/mirrors/mirrors.cgi?filename=/kafka/2.1.1/kafka_2.11-2.1.1.tgz&action=download" -O kafka.tgz
  - tar -xzf kafka.tgz
  - cd kafka_2.11-2.1.1
  - bin/zookeeper-server-start.sh config/zookeeper.properties >/dev/null 2>/dev/null &
  - bin/kafka-server-start.sh config/server.properties >/dev/null 2>/dev/null &
  - cd ../
