itemCount: 10
warehouseCount: 30
districtsPerWarehouse: 5
customersPerDistrict: 10
customerNameRange: 5
predictableData: true
verifierInstances: 1
workerInstances: 1
applicationInstances: 1
baseResultsDir: ~
modificationTopicPartitions: 1
