package net.jackw.olep.metrics;

public enum DurationType {
    DELIVERY_ACCEPTED,
    DELIVERY_COMPLETE,
    NEW_ORDER_ACCEPTED,
    NEW_ORDER_COMPLETE,
    NEW_ORDER_REJECTED,
    ORDER_STATUS_COMPLETE,
    PAYMENT_ACCEPTED,
    PAYMENT_COMPLETE,
    STOCK_LEVEL_COMPLETE
}
