package net.jackw.olep.metrics;

import net.jackw.olep.common.DatabaseConfig;

import javax.annotation.Nonnull;
import java.io.IOException;

/**
 * Logger for metrics generated by the program
 */
public abstract class Metrics {
    /**
     * Start a new timer
     */
    public Timer startTimer() {
        return Timer.start();
    }

    /**
     * Record a duration
     *
     * @param type The type of duration event that this corresponds to
     * @param timer The timer that was started when the event started
     */
    public abstract void recordDuration(DurationType type, Timer timer);

    /**
     * Record an instantaneous event
     *
     * @param type The type of event that is being recorded
     */
    public void recordEvent(EventType type) {
        recordEvent(type, "");
    }

    /**
     * Record an instantaneous event
     *
     * @param type The type of event that is being recorded
     * @param data Additional data about the event
     */
    public abstract void recordEvent(EventType type, @Nonnull String data);

    /**
     * Create a new metrics logger
     * @param mainClass The main class for this run
     * @param config The current database config
     * @return A metrics logger
     * @throws IOException If opening a DiskMetrics fails
     */
    public static Metrics create(String mainClass, DatabaseConfig config) throws IOException {
        if (config.getResultsDir() == null || config.getResultsDir().isBlank()) {
            return new InMemoryMetrics();
        } else {
            return new DiskMetrics(mainClass, config);
        }
    }
}
